semi: false
singleQuote: true
trailingComma: all
printWidth: 88
plugins:
  - prettier-plugin-tailwindcss
  - prettier-plugin-classnames
  - prettier-plugin-merge

# classnames
endingPosition: absolute-with-indent
